Grand.Web/Areas/Admin/Controllers/GiftCardController.cs
using Grand.Core;
using Grand.Framework.Controllers;
using Grand.Framework.Kendoui;
using Grand.Framework.Mvc.Filters;
using Grand.Framework.Security.Authorization;
using Grand.Services.Localization;
using Grand.Services.Orders;
using Grand.Services.Security;
using Grand.Web.Areas.Admin.Interfaces;
using Grand.Web.Areas.Admin.Models.Orders;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Grand.Web.Areas.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.GiftCards)]
    public partial class GiftCardController : BaseAdminController
    {
        #region Fields
        private readonly IGiftCardViewModelService _giftCardViewModelService;
        private readonly IGiftCardService _giftCardService;
        private readonly ILocalizationService _localizationService;
        #endregion

        #region Constructors

        public GiftCardController(
            IGiftCardViewModelService giftCardViewModelService,
            IGiftCardService giftCardService,
            ILocalizationService localizationService)
        {
            _giftCardViewModelService = giftCardViewModelService;
            _giftCardService = giftCardService;
            _localizationService = localizationService;
        }

        #endregion

        #region Methods

        //list
        public IActionResult Index() => RedirectToAction("List");

        public IActionResult List()
        {
            var model = _giftCardViewModelService.PrepareGiftCardListModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GiftCardList(DataSourceRequest command, GiftCardListModel model)
        {
            var (giftCardModels, totalCount) = await _giftCardViewModelService.PrepareGiftCardModel(model, command.Page, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = giftCardModels.ToList(),
                Total = totalCount
            };

            return Json(gridModel);
        }

        public async Task<IActionResult> Create()
        {
            var model = await _giftCardViewModelService.PrepareGiftCardModel();
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> Create(GiftCardModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                var giftCard = await _giftCardViewModelService.InsertGiftCardModel(model);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = giftCard.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            model = await _giftCardViewModelService.PrepareGiftCardModel(model);
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var giftCard = await _giftCardService.GetGiftCardById(id);
            if (giftCard == null)
                //No gift card found with the specified id
                return RedirectToAction("List");

            var model = await _giftCardViewModelService.PrepareGiftCardModel(giftCard);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public async Task<IActionResult> Edit(GiftCardModel model, bool continueEditing)
        {
            var giftCard = await _giftCardService.GetGiftCardById(model.Id);
            if (giftCard == null)
                return RedirectToAction("List");

            await _giftCardViewModelService.FillGiftCardModel(giftCard, model);

            if (ModelState.IsValid)
            {
                giftCard = await _giftCardViewModelService.UpdateGiftCardModel(giftCard, model);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Updated"));

                if (continueEditing)
                {
                    //selected tab
                    await SaveSelectedTabIndex();

                    return RedirectToAction("Edit", new { id = giftCard.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public IActionResult GenerateCouponCode()
        {
            return Json(new { CouponCode = _giftCardService.GenerateGiftCardCode() });
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notifyRecipient")]
        public async Task<IActionResult> NotifyRecipient(GiftCardModel model)
        {
            var giftCard = await _giftCardService.GetGiftCardById(model.Id);

            if (!CommonHelper.IsValidEmail(giftCard.RecipientEmail))
                ModelState.AddModelError("", "Recipient email is not valid");
            if (!CommonHelper.IsValidEmail(giftCard.SenderEmail))
                ModelState.AddModelError("", "Sender email is not valid");

            try
            {
                if (ModelState.IsValid)
                {
                    await _giftCardViewModelService.NotifyRecipient(giftCard, model);
                }
                else
                    ErrorNotification(ModelState);
            }
            catch (Exception exc)
            {
                ErrorNotification(exc, false);
            }
            model = await _giftCardViewModelService.PrepareGiftCardModel(giftCard);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var giftCard = await _giftCardService.GetGiftCardById(id);
            if (giftCard == null)
                //No gift card found with the specified id
                return RedirectToAction("List");

            if (giftCard.GiftCardUsageHistory.Any())
                ModelState.AddModelError("", _localizationService.GetResource("Admin.GiftCards.PreventDeleted"));

            if (ModelState.IsValid)
            {
                await _giftCardViewModelService.DeleteGiftCard(giftCard);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Deleted"));
                return RedirectToAction("List");
            }
            ErrorNotification(ModelState);
            return RedirectToAction("Edit", new { id = giftCard.Id });
        }

        //Gif card usage history
        [HttpPost]
        public async Task<IActionResult> UsageHistoryList(string giftCardId, DataSourceRequest command)
        {
            var giftCard = await _giftCardService.GetGiftCardById(giftCardId);
            if (giftCard == null)
                throw new ArgumentException("No gift card found with the specified id");

            var (giftCardUsageHistoryModels, totalCount) = await _giftCardViewModelService.PrepareGiftCardUsageHistoryModels(giftCard, command.Page, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = giftCardUsageHistoryModels.ToList(),
                Total = totalCount
            };

            return Json(gridModel);
        }

        #endregion
    }
}

Grand.Web/Controllers/OrderController.cs
using Grand.Core;
using Grand.Domain.Customers;
using Grand.Domain.Orders;
using Grand.Domain.Shipping;
using Grand.Framework.Controllers;
using Grand.Services.Commands.Models.Orders;
using Grand.Services.Common;
using Grand.Services.Localization;
using Grand.Services.Orders;
using Grand.Services.Payments;
using Grand.Services.Shipping;
using Grand.Web.Commands.Models.Orders;
using Grand.Web.Events;
using Grand.Web.Features.Models.Orders;
using Grand.Web.Models.Orders;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Grand.Web.Extensions;

namespace Grand.Web.Controllers
{
    public partial class OrderController : BasePublicController
    {
        #region Fields

        private readonly IOrderService _orderService;
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IPaymentService _paymentService;
        private readonly ILocalizationService _localizationService;
        private readonly IMediator _mediator;
        private readonly OrderSettings _orderSettings;

        #endregion

        #region Constructors

        public OrderController(IOrderService orderService,
            IWorkContext workContext,
            IStoreContext storeContext,
            IOrderProcessingService orderProcessingService,
            IPaymentService paymentService,
            ILocalizationService localizationService,
            IMediator mediator,
            OrderSettings orderSettings)
        {
            _orderService = orderService;
            _workContext = workContext;
            _storeContext = storeContext;
            _orderProcessingService = orderProcessingService;
            _paymentService = paymentService;
            _localizationService = localizationService;
            _mediator = mediator;
            _orderSettings = orderSettings;
        }

        #endregion

        #region Methods

        //My account / Orders
        public virtual async Task<IActionResult> CustomerOrders()
        {
            if (!_workContext.CurrentCustomer.IsRegistered())
                return Challenge();

            var model = await _mediator.Send(new GetCustomerOrderList() {
                Customer = _workContext.CurrentCustomer,
                Language = _workContext.WorkingLanguage,
                Store = _storeContext.CurrentStore
            });
            return View(model);
        }

        //My account / Orders / Cancel recurring order
        [HttpPost, ActionName("CustomerOrders")]
        [AutoValidateAntiforgeryToken]
        [FormValueRequired(FormValueRequirement.StartsWith, "cancelRecurringPayment")]
        public virtual async Task<IActionResult> CancelRecurringPayment(IFormCollection form)
        {
            if (!_workContext.CurrentCustomer.IsRegistered())
                return Challenge();

            //get recurring payment identifier
            string recurringPaymentId = "";
            foreach (var formValue in form.Keys)
                if (formValue.StartsWith("cancelRecurringPayment", StringComparison.OrdinalIgnoreCase))
                    recurringPaymentId = formValue.Substring("cancelRecurringPayment".Length);

            var recurringPayment = await _orderService.GetRecurringPaymentById(recurringPaymentId);
            if (recurringPayment == null)
            {
                return RedirectToRoute("CustomerOrders");
            }

            if (await _orderProcessingService.CanCancelRecurringPayment(_workContext.CurrentCustomer, recurringPayment))
            {
                var errors = await _orderProcessingService.CancelRecurringPayment(recurringPayment);

                var model = await _mediator.Send(new GetCustomerOrderList() {
                    Customer = _workContext.CurrentCustomer,
                    Language = _workContext.WorkingLanguage,
                    Store = _storeContext.CurrentStore
                });
                model.CancelRecurringPaymentErrors = errors;

                return View(model);
            }
            else
            {
                return RedirectToRoute("CustomerOrders");
            }
        }

        //My account / Reward points
        public virtual async Task<IActionResult> CustomerRewardPoints([FromServices] RewardPointsSettings rewardPointsSettings)
        {
            if (!_workContext.CurrentCustomer.IsRegistered())
                return Challenge();

            if (!rewardPointsSettings.Enabled)
                return RedirectToRoute("CustomerInfo");

            var model = await _mediator.Send(new GetCustomerRewardPoints() {
                Customer = _workContext.CurrentCustomer,
                Store = _storeContext.CurrentStore,
                Currency = _workContext.WorkingCurrency
            });
            return View(model);
        }

        //My account / Order details page
        public virtual async Task<IActionResult> Details(string orderId)
        {
            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            var model = await _mediator.Send(new GetOrderDetails() { Order = order, Language = _workContext.WorkingLanguage });

            return View(model);
        }

        //My account / Order details page / Print
        public virtual async Task<IActionResult> PrintOrderDetails(string orderId)
        {
            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            var model = await _mediator.Send(new GetOrderDetails() { Order = order, Language = _workContext.WorkingLanguage });
            model.PrintMode = true;

            return View("Details", model);
        }

        //My account / Order details page / Cancel Unpaid Order
        public virtual async Task<IActionResult> CancelOrder(string orderId)
        {
            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer) || order.PaymentStatus != Domain.Payments.PaymentStatus.Pending
                || (order.ShippingStatus != ShippingStatus.ShippingNotRequired && order.ShippingStatus != ShippingStatus.NotYetShipped)
                || order.OrderStatus != OrderStatus.Pending
                || !_orderSettings.UserCanCancelUnpaidOrder)

                return Challenge();

            await _mediator.Send(new CancelOrderCommand() { Order = order, NotifyCustomer = true, NotifyStoreOwner = true });

            return RedirectToRoute("OrderDetails", new { orderId = orderId });
        }

        //My account / Order details page / PDF invoice
        public virtual async Task<IActionResult> GetPdfInvoice(string orderId, [FromServices] IPdfService pdfService)
        {
            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            var orders = new List<Order>();
            orders.Add(order);
            byte[] bytes;
            using (var stream = new MemoryStream())
            {
                await pdfService.PrintOrdersToPdf(stream, orders, _workContext.WorkingLanguage.Id);
                bytes = stream.ToArray();
            }
            return File(bytes, "application/pdf", string.Format("order_{0}.pdf", order.Id));
        }

        //My account / Order details page / Add order note
        public virtual async Task<IActionResult> AddOrderNote(string orderId)
        {
            if (!_orderSettings.AllowCustomerToAddOrderNote)
                return RedirectToRoute("HomePage");

            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            var model = new AddOrderNoteModel();
            model.OrderId = orderId;
            return View("AddOrderNote", model);
        }

        //My account / Order details page / Add order note
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public virtual async Task<IActionResult> AddOrderNote(AddOrderNoteModel model)
        {
            if (!_orderSettings.AllowCustomerToAddOrderNote)
                return RedirectToRoute("HomePage");

            if (!ModelState.IsValid)
            {
                return View("AddOrderNote", model);
            }

            var order = await _orderService.GetOrderById(model.OrderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            await _mediator.Send(new InsertOrderNoteCommand() { Order = order, OrderNote = model, Language = _workContext.WorkingLanguage });

            //notification
            await _mediator.Publish(new OrderNoteEvent(order, model));

            AddNotification(Framework.UI.NotifyType.Success, _localizationService.GetResource("OrderNote.Added"), true);
            return RedirectToRoute("OrderDetails", new { orderId = model.OrderId });
        }

        //My account / Order details page / re-order
        public virtual async Task<IActionResult> ReOrder(string orderId)
        {
            var order = await _orderService.GetOrderById(orderId);
            if (!order.Access(_workContext.CurrentCustomer))
                return Challenge();

            var warnings = await _mediator.Send(new ReOrderCommand() { Order = order });
            if(warnings.Any())
                AddNotification(Framework.UI.NotifyType.Error, string.Join(",", warnings), true);

            return RedirectToRoute("ShoppingCart");
        }

        //My account / Order details page / Complete payment

Grand.Web/Areas/Admin/Views/GiftCard/Create.cshtml
@model GiftCardModel
@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.AddNew").Text;
}
<form asp-area="Admin" asp-controller="GiftCard" asp-action="Create" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>
                        @T("Admin.GiftCards.AddNew")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.GiftCards.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions btn-group btn-group-devided">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        <vc:admin-widget widget-zone="gift_card_details_buttons" additional-data="null" />
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

Grand.Web/Areas/Admin/Views/GiftCard/Edit.cshtml
@model GiftCardModel
@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.EditGiftCardDetails").Text;
}
<form asp-area="Admin" asp-controller="GiftCard" asp-action="Edit" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>
                        @T("Admin.GiftCards.EditGiftCardDetails")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.GiftCards.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions btn-group btn-group-devided">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        <span id="giftcard-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                        <vc:admin-widget widget-zone="gift_card_details_buttons" additional-data="null" />
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>
<admin-delete-confirmation button-id="giftcard-delete"/>

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.TabHistory.cshtml
@model GiftCardModel
@inject AdminAreaSettings adminAreaSettings
@{
    <vc:admin-widget widget-zone="gift_card_details_history_top" additional-data="Model" />
    <div id="usagehistory-grid"></div>
    <vc:admin-widget widget-zone="gift_card_details_history_bottom" additional-data="Model" />
    <script>
        $(document).ready(function () {
            $("#usagehistory-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("UsageHistoryList", "GiftCard", new { giftCardId = Model.Id }))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "CreatedOn",
                    title: "@T("Admin.GiftCards.History.CreatedOn")",
                    width: 200,
                    type: "date",
                    format: "{0:G}"
                }, {
                    field: "OrderId",
                    title: "@T("Admin.GiftCards.History.Order")",
                    width: 200,
                        template: '<a href="@Url.Content("~/Admin/Order/Edit/")#=OrderId#" class="k-button"><span class="k-icon k-i-eye"></span>&nbsp;@T("Admin.Common.View") #=OrderNumber#</a>'
                }, {
                    field: "UsedValue",
                    title: "@T("Admin.GiftCards.History.UsedValue")",
                    width: 200
                }]
            });
        });
    </script>
}

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.TabInfo.cshtml
@model GiftCardModel
<script>
    $(document).ready(function () {
        $("#@Html.FieldIdFor(model => model.GiftCardTypeId)").change(toggleGiftCardType);
        toggleGiftCardType();
    });

    function toggleGiftCardType() {
        var selectedGiftCardTypeId = $("#@Html.FieldIdFor(model => model.GiftCardTypeId)").val();
        if (selectedGiftCardTypeId == @(((int)GiftCardType.Virtual).ToString())) {
            $('#pnlRecipientEmail').show();
            $('#pnlSenderEmail').show();
            $('#pnlNotifyRecipient').show();
        }
        else {
            $('#pnlRecipientEmail').hide();
            $('#pnlSenderEmail').hide();
            $('#pnlNotifyRecipient').hide();
        }
    }
</script>
<div class="form-horizontal">
    <vc:admin-widget widget-zone="gift_card_details_info_top" additional-data="Model" />
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="GiftCardTypeId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="GiftCardTypeId" asp-items="((GiftCardType)Model.GiftCardTypeId).ToSelectList(Context)" />
                <span asp-validation-for="GiftCardTypeId"></span>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.PurchasedWithOrderId))
        {
            <div class="form-group">
                <admin-label asp-for="PurchasedWithOrderId" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label"><a href="@Url.Action("Edit", "Order", new { Id = Model.PurchasedWithOrderId })" class="k-button"><span class="k-icon k-i-eye"></span>&nbsp;@T("Admin.Common.View") #@Model.PurchasedWithOrderNumber</a></label>
                </div>
            </div>
        }
        <div class="form-group">
            <admin-label asp-for="Amount" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Amount" /> [@Model.PrimaryStoreCurrencyCode]
                <span asp-validation-for="Amount"></span>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group">
                <admin-label asp-for="RemainingAmountStr" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label">@Model.RemainingAmountStr</label>
                </div>
            </div>
        }
        <div class="form-group">
            <admin-label asp-for="IsGiftCardActivated" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="IsGiftCardActivated" />
                     <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="IsGiftCardActivated"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="GiftCardCouponCode" />
            <div class="col-md-4 col-sm-6">
                <div class="input-group">
                    <div class="input-group-control">
                        <admin-input asp-for="GiftCardCouponCode" />
                    </div>
                    <div class="input-group-btn">
                        <input type="button" id="generateCouponCode" class="btn default" value="@T("Admin.GiftCards.Fields.GiftCardCouponCode.Generate")" />
                    </div>
                </div>
                <span asp-validation-for="GiftCardCouponCode"></span>
                <script>
                        $(document).ready(function () {
                            $('#generateCouponCode').click(function () {

                                var postData = {
                                };
                                addAntiForgeryToken(postData);

                                $.ajax({
                                    cache:false,
                                    type: "POST",
                                    url: "@(Url.Action("GenerateCouponCode", "GiftCard"))",
                                    data: postData,
                                    success: function (data) {
                                        $('#@Html.FieldIdFor(model => model.GiftCardCouponCode)').val(data.CouponCode);
                                    },
                                    error:function (xhr, ajaxOptions, thrownError){
                                        alert('Failed to generate code.');
                                    }
                                });
                            });
                        });
                </script>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="RecipientName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="RecipientName" />
                <span asp-validation-for="RecipientName"></span>
            </div>
        </div>
        <div class="form-group" id="pnlRecipientEmail">
            <admin-label asp-for="RecipientEmail" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="RecipientEmail" />
                <span asp-validation-for="RecipientEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="SenderName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SenderName" />
                <span asp-validation-for="SenderName"></span>
            </div>
        </div>
        <div class="form-group" id="pnlSenderEmail">
            <admin-label asp-for="SenderEmail" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SenderEmail" />
                <span asp-validation-for="SenderEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Message" />
            <div class="col-md-9 col-sm-9">
                <admin-textarea asp-for="Message"></admin-textarea>
                <span asp-validation-for="Message"></span>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group" id="pnlNotifyRecipient">
                <admin-label asp-for="IsRecipientNotified" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label">@Model.IsRecipientNotified.ToString()</label>
                    <button type="submit" name="notifyRecipient" class="k-button"><span class="k-icon k-i-notification"></span>&nbsp;@T("Admin.GiftCards.Fields.IsRecipientNotified.Notify")</button>
                </div>
            </div>
        }
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group">
                <admin-label asp-for="CreatedOn" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label"> @Model.CreatedOn</label>
                </div>
            </div>
        }
    </div>
    <vc:admin-widget widget-zone="gift_card_details_info_bottom" additional-data="Model" />
</div>

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.cshtml
@model GiftCardModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<admin-tabstrip name="giftcard-edit">
    <items>
        <tabstrip-item text="@T("Admin.GiftCards.Info")" tab-index="0">
            <content>
                <div>
                    <partial name="_CreateOrUpdate.TabInfo" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <tabstrip-item text="@T("Admin.GiftCards.History")" tab-index="1">
                <content>
                    <div>
                        <partial name="_CreateOrUpdate.TabHistory" model="Model" />
                    </div>
                </content>
            </tabstrip-item>
        }
        <vc:admin-widget widget-zone="giftcard_details_tabs" additional-data="Model" />
    </items>
</admin-tabstrip>